name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          plugin_code: yes
          plugin_code_lines: 128
          plugin_code_languages: javascript, typescript, c++, rust
          plugin_starlists: true
          # plugin_starlists_limit: 8
          # plugin_starlists_limit_repositories: 100
          plugin_starlists_languages: true
          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_details: percentage
          plugin_languages_ignored: c, objective-c
          plugin_languages_sections: recently-used, most-used
